### PR TITLE
update to FCS 26.0.1 to allow FSAC to update as well

### PR DESCRIPTION
**Pull request by baronfel**
Need to update FCS dependency so that FSAC is able to update the FCS dependency.

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
Thanks!

**Comment by baronfel** [comment]
Hey! Could you push to nuget so I can flow through the rest of the FCS update?

**Comment by Krzysztof-Cieslak** [comment]
Package released, it should be online after NuGet does it magic

**Comment by baronfel** [comment]
you rock

**Pull request merged**
